path_bags: '../Downloads/bags_uvdar'

bag_names: [
  'sim_uav1.bag', 'sim_uav2.bag', 'sim_uav3.bag',
]

uav_names: [
  'uav1', 'uav2', 'uav3',
]

time_step: 1.0 # [s]

path_output: '../Downloads/bags_uvdar/csv'